// <auto-generated />
using System;
using KAST.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAST.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KastDbContext))]
    [Migration("20260620022843_AddPerformanceColumnsToServerInstance")]
    partial class AddPerformanceColumnsToServerInstance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("KAST.Core.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("KAST.Core.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("KAST.Core.Models.CampaignMission", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("CampaignId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("CampaignMissions");
                });

            modelBuilder.Entity("KAST.Core.Models.DownloadTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("InstalledManifestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("DownloadTasks");
                });

            modelBuilder.Entity("KAST.Core.Models.HeadlessClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("HeadlessClients");
                });

            modelBuilder.Entity("KAST.Core.Models.KastSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arma3ServerAppId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUpdateCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionDownloadBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModsDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParallelDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParallelModDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServersDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemAuthDomain")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SystemAuthEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemAuthSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("KAST.Core.Models.KastUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("ExternalIssuer", "ExternalSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KAST.Core.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Hash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModPresetId");

                    b.HasIndex("ServerInstanceId");

                    b.HasIndex("ServerInstanceId", "FileName")
                        .IsUnique();

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("KAST.Core.Models.MissionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId", "Name")
                        .IsUnique();

                    b.ToTable("MissionTags");
                });

            modelBuilder.Entity("KAST.Core.Models.MissionTagAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId", "MissionTagId");

                    b.HasIndex("MissionTagId");

                    b.ToTable("MissionTagAssignments");
                });

            modelBuilder.Entity("KAST.Core.Models.ModPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawHtmlContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("ModPresets");
                });

            modelBuilder.Entity("KAST.Core.Models.ModPresetEntry", b =>
                {
                    b.Property<int>("ModPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SteamModId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClientSide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServerSide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModPresetId", "SteamModId");

                    b.HasIndex("SteamModId");

                    b.ToTable("ModPresetEntries");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmaProfileContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoStopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicCfgContent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContactDlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CpuCountOverride")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CslaDlc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EfDlc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableHT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRanking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GmDlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadlessClientCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HttpDownloadsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledBuildId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxMem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaxMemOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRestartAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PfDlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RfDlc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScheduleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerCfgContent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpeDlc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SteamQueryPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WsDlc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServerInstances");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstanceMod", b =>
                {
                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SteamModId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClientSide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServerSide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerInstanceId", "SteamModId");

                    b.HasIndex("SteamModId");

                    b.ToTable("ServerInstanceMods");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstanceProcessHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminationReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.HasIndex("ServerInstanceId", "EndedAt");

                    b.ToTable("ServerInstanceProcessHistories");
                });

            modelBuilder.Entity("KAST.Core.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("KAST.Core.Models.SetMission", b =>
                {
                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("SetMissions");
                });

            modelBuilder.Entity("KAST.Core.Models.SteamMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("InstalledManifestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClientSide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServerSide")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedSteam")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SteamManifestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId")
                        .IsUnique();

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("KAST.Core.Models.Campaign", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.CampaignMission", b =>
                {
                    b.HasOne("KAST.Core.Models.Campaign", "Campaign")
                        .WithMany("CampaignMissions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Core.Models.Mission", "Mission")
                        .WithMany("CampaignMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAST.Core.Models.DownloadTask", b =>
                {
                    b.HasOne("KAST.Core.Models.SteamMod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("KAST.Core.Models.HeadlessClient", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("HeadlessClients")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.Mission", b =>
                {
                    b.HasOne("KAST.Core.Models.ModPreset", "ModPreset")
                        .WithMany("Missions")
                        .HasForeignKey("ModPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModPreset");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.MissionTag", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.MissionTagAssignment", b =>
                {
                    b.HasOne("KAST.Core.Models.Mission", "Mission")
                        .WithMany("TagAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Core.Models.MissionTag", "Tag")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("MissionTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("KAST.Core.Models.ModPreset", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.ModPresetEntry", b =>
                {
                    b.HasOne("KAST.Core.Models.ModPreset", "ModPreset")
                        .WithMany("Entries")
                        .HasForeignKey("ModPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Core.Models.SteamMod", "SteamMod")
                        .WithMany()
                        .HasForeignKey("SteamModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModPreset");

                    b.Navigation("SteamMod");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstanceMod", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Mods")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Core.Models.SteamMod", "SteamMod")
                        .WithMany("ServerInstances")
                        .HasForeignKey("SteamModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");

                    b.Navigation("SteamMod");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstanceProcessHistory", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.Set", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.SetMission", b =>
                {
                    b.HasOne("KAST.Core.Models.Mission", "Mission")
                        .WithMany("SetMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Core.Models.Set", "Set")
                        .WithMany("SetMissions")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("KAST.Core.Models.Campaign", b =>
                {
                    b.Navigation("CampaignMissions");
                });

            modelBuilder.Entity("KAST.Core.Models.Mission", b =>
                {
                    b.Navigation("CampaignMissions");

                    b.Navigation("SetMissions");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("KAST.Core.Models.MissionTag", b =>
                {
                    b.Navigation("MissionAssignments");
                });

            modelBuilder.Entity("KAST.Core.Models.ModPreset", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Missions");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstance", b =>
                {
                    b.Navigation("HeadlessClients");

                    b.Navigation("Mods");
                });

            modelBuilder.Entity("KAST.Core.Models.Set", b =>
                {
                    b.Navigation("SetMissions");
                });

            modelBuilder.Entity("KAST.Core.Models.SteamMod", b =>
                {
                    b.Navigation("ServerInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
