// <auto-generated />
using System;
using KAST.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAST.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KastDbContext))]
    [Migration("20260402084804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("KAST.Core.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("KAST.Core.Models.DownloadTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DownloadTasks");
                });

            modelBuilder.Entity("KAST.Core.Models.HeadlessClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("HeadlessClients");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoStopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicCfgContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadlessClientCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRestartAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScheduleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerCfgContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerProfileContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SteamQueryPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServerInstances");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstanceMod", b =>
                {
                    b.Property<int>("ServerInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SteamModId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsServerSide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerInstanceId", "SteamModId");

                    b.HasIndex("SteamModId");

                    b.ToTable("ServerInstanceMods");
                });

            modelBuilder.Entity("KAST.Core.Models.SteamMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClientSide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServerSide")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdatedLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedSteam")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId")
                        .IsUnique();

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("KAST.Core.Models.HeadlessClient", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("HeadlessClients")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstanceMod", b =>
                {
                    b.HasOne("KAST.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Mods")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Core.Models.SteamMod", "SteamMod")
                        .WithMany("ServerInstances")
                        .HasForeignKey("SteamModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");

                    b.Navigation("SteamMod");
                });

            modelBuilder.Entity("KAST.Core.Models.ServerInstance", b =>
                {
                    b.Navigation("HeadlessClients");

                    b.Navigation("Mods");
                });

            modelBuilder.Entity("KAST.Core.Models.SteamMod", b =>
                {
                    b.Navigation("ServerInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
